version: '3.8'

services:
  # Node.js Express REST API Server
  api:
    build: .
    container_name: ecommerce-express-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=super_secret_jwt_key_store_2026_production
      - JWT_EXPIRES_IN=7d
      - MONGODB_URI=mongodb://mongo:27017/ecommerce_db
      - CORS_ORIGIN=*
    depends_on:
      - mongo

  # MongoDB Database Service
  mongo:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # Optional Mongo Web GUI Admin
  mongo-express:
    image: mongo-express:latest
    container_name: ecommerce-mongo-gui
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongo

volumes:
  mongo_data:
